### ISSUE TITLE
The step always reset to 0 when I update the APP or uninstall and reinstall !?

### ISSUE THREAD

**Issue by trungphan9x** [0xf4b1/motionmate#2]
Are there any way to not loose the step when you update the APP or uninstall and reinstall it again? The step always reset to 0 when I update the APP or uninstall and reinstall !?

**Comment by tiefensuche** [comment]
Uninstalling will delete all the app's data, same as for any other app. But updating to a newer version will keep the data. I just needed to sign the apk on the releases page, because normally you can not install an unsigned apk on android. This makes the signed apk incompatible with any unsigned or differently signed apk.
